# ================================================================
# AutoSetupスクリプト設定ファイル
# ================================================================
# 実行したいタスクをフェーズごとに定義します。
# 不要な項目は、行頭に「#」を付けてコメントアウトするとスキップされます。

# ----------------------------------------------------------------
# ■ フェーズ1: システムの基本セットアップ
# ----------------------------------------------------------------
phase1:
  # --- Windowsのシステム設定変更 ---
  windowsTweaks:
    - description: 隠しファイルとフォルダを表示する
      command: 'reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v Hidden /t REG_DWORD /d 1 /f'

    - description: ファイルの拡張子を常に表示する
      command: 'reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v HideFileExt /t REG_DWORD /d 0 /f'

    - description: エクスプローラーのアドレスバーに完全なパスを表示する
      command: 'reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\CabinetState" /v FullPathAddress /t REG_DWORD /d 1 /f'

    - description: エクスプローラーの起動時に「PC」を表示する
      command: 'reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v LaunchTo /t REG_DWORD /d 1 /f'

    - description: 高速スタートアップを無効化する (powercfgコマンド)
      command: "powercfg.exe /h off"

    - description: 電源接続時のスリープを無効にする
      command: "powercfg /change standby-timeout-ac 0"

    - description: バッテリー駆動時のスリープを無効にする
      command: "powercfg /change standby-timeout-dc 0"

    - description: 右クリックメニューを従来のスタイルに戻す (Win11)
      command: 'reg add "HKCU\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32" /f'

  # --- Wingetによるアプリケーションのインストール ---
  wingetInstall:
    - id: Microsoft.PowerShell                 # 最新のPowerShell
    - id: Google.Chrome                        # Webブラウザ
    - id: 7zip.7zip                            # 高性能なファイル圧縮・解凍ソフト
    - id: Microsoft.PowerToys                  # Windowsを便利にするユーティリティ集
    - id: Zoom.Zoom                            # Web会議ツール
    - id: Git.Git                              # バージョン管理システム
    - id: OpenJS.NodeJS.LTS                    # JavaScript実行環境 (長期サポート版)
    - id: Python.Python.3.12                   # プログラミング言語 Python
    - id: astral-sh.uv                         # 高速なPythonパッケージインストーラー
    - id: Microsoft.VisualStudioCode           # 統合開発環境 (IDE)
      options: '--override "/SILENT /NORESTART /MERGETASKS=!runcode,desktopicon,addcontextmenufiles,addcontextmenufolders,associatewithfiles,addtopath"'
    - id: Adobe.Acrobat.Reader.64-bit          # PDF閲覧ソフト
      options: '--override "/sAll /rs /rps /msi EULA_ACCEPT=YES"'

  # --- 不要なプリインストールアプリの削除 ---
  appxRemove:
    - name: "*Cortana*"                        # AIアシスタント
    - name: "*Microsoft.BingNews*"             # ニュースアプリ
    - name: "*Microsoft.GetHelp*"              # ヘルプ表示アプリ
    - name: "*Microsoft.Getstarted*"           # ヒント表示アプリ
    - name: "*Microsoft.Office.OneNote*"       # OneNote (ストアアプリ版)
    - name: "*Microsoft.People*"               # People (連絡先) アプリ
    - name: "*Microsoft.WindowsFeedbackHub*"   # フィードバックHub
    - name: "*Microsoft.YourPhone*"            # スマートフォン連携
    - name: "*Microsoft.ZuneMusic*"            # Grooveミュージック
    - name: "*Microsoft.ZuneVideo*"            # 映画 & テレビ

# ----------------------------------------------------------------
# ■ フェーズ2: 開発者向けパッケージのインストール（再起動後）
# ----------------------------------------------------------------
phase2:
  # =================================================================
  # ■ パッケージマネージャーとインストールするパッケージの定義
  # =================================================================
  packageManagers:
    # --- npm (Node.js) の設定 ---
    - managerName: 'npm'                                            # 管理者の表示名 (ログ用)
      checkCommand: 'npm list -g {package} --depth=0'               # インストール済みか確認するコマンド。{package}は置換される。成功(インストール済)の場合、終了コード0を返すこと。
      installCommand: 'npm install -g {package}'                    # インストールを実行するコマンド。{package}は置換される。
      packages:                                                     # このマネージャーでインストールするパッケージのリスト
        - typescript                                                # 静的型付けJavaScript
        - ts-node                                                   # TypeScriptを直接実行
        - nodemon                                                   # ファイル変更時に自動でサーバーを再起動
        - eslint                                                    # コードの静的解析ツール
        - prettier                                                  # コードフォーマッター
        - pnpm                                                      # 高速なパッケージマネージャー

    # --- pip (Python) の設定 (uvを使用) ---
    - managerName: 'pip'                                            # 管理者の表示名 (ログ用)
      checkCommand: 'uv pip show {package}'                         # インストール済みか確認するコマンド。{package}は置換される。
      installCommand: 'uv pip install {package} --system'           # インストールを実行するコマンド。{package}は置換される。
      packages:                                                     # このマネージャーでインストールするパッケージのリスト
        - jupyterlab                                                # 対話的なデータ分析・開発環境
        - jupyterlab-language-pack-ja-jp                            # JupyterLabの日本語化パック
        - requests                                                  # HTTP通信ライブラリ
        - numpy                                                     # 数値計算ライブラリ
        - pandas                                                    # データ分析ライブラリ
        - matplotlib                                                # データ可視化・グラフ描画ライブラリ
        - black                                                     # コードフォーマッター
        - ruff                                                      # 高速なリンター
        - python-dotenv                                             # .envファイルから環境変数を読み込む
        - scikit-learn                                              # 機械学習ライブラリ
        - seaborn                                                   # 統計的データ可視化ライブラリ
        - openpyxl                                                  # Excelファイルの読み書き
        - fastapi                                                   # 高速なWebフレームワーク
        - lxml                                                      # XML/HTMLパーサー

    # --- cargo (Rust) の設定例 ---
    # 注: cargoの確認コマンドはパイプライン(|)を含むため、このスクリプトでは直接サポートしていません。
    # checkCommandを修正するか、インストール済でも再実行を許容する運用を検討してください。
    # - managerName: 'cargo'                                         # 管理者の表示名 (ログ用)
    #   checkCommand: 'cargo install --list | findstr {package}'     # インストール済みか確認するコマンド。{package}は置換される。
    #   installCommand: 'cargo install {package}'                    # インストールを実行するコマンド。{package}は置かなければならない。
    #   packages:                                                    # このマネージャーでインストールするパッケージのリスト
    #     - ripgrep                                                  # 高速なgrep代替ツール
    #     - bat                                                      # シンタックスハイライト付きcat
    #     - fd-find                                                  # 高速なfind代替ツール