# ワークフローの名前。GitHubの "Actions" タブで表示されます。
name: PowerShell AutoSetup Script CI

# このワークフローが実行されるタイミング（トリガー）を指定します。
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# 実行する一連のジョブを定義します。
jobs:
  run-script-on-windows:
    runs-on: windows-latest
    steps:
    # ステップ1: リポジトリのコードを仮想マシンにダウンロードします。
    - name: Checkout repository code
      uses: actions/checkout@v4

    # ステップ2: フェーズ1を実行します。
    # スクリプト実行前に'winget'コマンドのエイリアス（別名）を直接作成します。
    - name: Run AutoSetup Phase 1
      shell: powershell
      run: |
        New-Alias -Name winget -Value "$env:LOCALAPPDATA\Microsoft\WindowsApps\winget.exe" -ErrorAction Stop
        Write-Host "Alias 'winget' created successfully."
        .\AutoSetup.ps1

    # ステップ3: フェーズ2を実行します。
    # ステップが異なるため、ここでも再度エイリアスを作成する必要があります。
    - name: Run AutoSetup Phase 2
      shell: powershell
      run: |
        New-Alias -Name winget -Value "$env:LOCALAPPDATA\Microsoft\WindowsApps\winget.exe" -ErrorAction Stop
        Write-Host "Alias 'winget' created successfully."
        .\AutoSetup.ps1 -SetupPhase 2