# ワークフローの名前。GitHubの "Actions" タブで表示されます。
name: PowerShell AutoSetup Script CI

# このワークフローが実行されるタイミング（トリガー）を指定します。
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# 実行する一連のジョブを定義します。
jobs:
  run-script-on-windows:
    runs-on: windows-latest
    steps:
    # ステップ1: リポジトリのコードを仮想マシンにダウンロードします。
    - name: Checkout repository code
      uses: actions/checkout@v4

    # ステップ2: wingetのパスを追加し、続けてフェーズ1を実行します。
    # 同一のステップ内で実行することで、環境変数の変更を確実に反映させます。
    - name: Run AutoSetup Phase 1 with winget path
      shell: pwsh
      run: |
        $env:PATH = "$env:PATH;$env:LOCALAPPDATA\Microsoft\WindowsApps"
        .\AutoSetup.ps1

    # ステップ3: wingetのパスを追加し、続けてフェーズ2を実行します。
    # ステップが異なると環境変数はリセットされるため、ここでも再度パスを設定します。
    - name: Run AutoSetup Phase 2 with winget path
      shell: pwsh
      run: |
        $env:PATH = "$env:PATH;$env:LOCALAPPDATA\Microsoft\WindowsApps"
        .\AutoSetup.ps1 -SetupPhase 2